# 최상위 경로의 values.yaml

ingressRule:
  namespace: "default"
  host: "cloudyim.store"

image-frontend:
  replicaCount: 2
  image:
    tag: "1.0"
  service:
    port: 80
  containerPort: 80
  enabled: true

image-backend:
  replicaCount: 2
  image:
    tag: "1.0"
  service:
    port: 8000
  containerPort: 8000
  enabled: true
