apiVersion: v2
name: msa-platform
description: "image-front + image-backend"
type: application
version: 0.1.0 # chart 의 버전 
appVersion: "1.0.0" # application 의 버전

# 의존하는 dependency chart 목록
dependencies:
  - name: image-frontend
    version: "0.1.0"
    # "file://하위 chart 의 경로를 작성"
    repository: "file://charts/image-frontend"
    # 하위 chart 를 무조건 포함하는것이 아니고 조건부로 포함 하겠다는 의미 
    condition: image-frontend.enabled 

  - name: image-backend
    version: "0.1.0"
    repository: "file://charts/image-backend"
    condition: image-backend.enabled