# efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim           # 이름을 deploy.yaml에서 호출
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc  # storage class name 일치시키기
  resources:
    requests:
      storage: 5Gi          # PV에 적은 용량과 똑같이 맞춰줍니다.