# init.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pg-db-secret
type: Opaque
stringData:
  username: scott
  password: tiger
  database: scott_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-db-init-sql
data:
  init.sql: |
    SET ROLE scott;
    DO $$ 
    BEGIN
        IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'member') THEN
            CREATE TABLE member(num SERIAL PRIMARY KEY, name VARCHAR(20), addr TEXT);
            INSERT INTO member (name, addr) VALUES('kim', 'seoul');
            INSERT INTO member (name, addr) VALUES('lee', 'pusan');
        END IF;
    END $$;